apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: repository-secret
  namespace: argocd
spec:
  template:
    metadata:
      name: repository-secret
      namespace: argocd
  encryptedData:
    sshPrivateKey: AgCo+G5KXRS4wAs9KdxHgNzUE2tMsYC4S6K795HiqMhIarnZ9AFNGVRzWCG1gbYkx+aXaOK2yT2hbKu5G2sMGwpNSu0SVuQq48cWTXMRg1p5ACAdbX6MU6TVkFHlt64QpRDmhkGQ6yaaKVkYHndfS2l1HVf5KaJx06m6bMP3KR8mzSnF4vpkpJ7DGzyPnzqKZ7gyxy+w5qoJyk0R4OJuUuj8GIVUtvsKkNbv/oI4VSvweVctmeCrvj+xjLOQ4cCZ+X8WBhHvnlmHQ9QX3h1I8MHSsUXaYM3Ps3sdP5zHR/ejxW1nQNe9zx0HOXUgsCmou3B/hYbQu18KTUBxov/h4yplLoUnVlceMIB+YjSo3SGZ7uml22Q2LAYGfE7IgmY4ycFkvBJv43talq4xtmDBv+u27kHYxlyd6D0UHcjkhWZZsg6yxh05YDDD+njIFGCnyE8IaOlN7CSCSzVt+sZ71kC0YB44pcIV52xW9WyZXp+yHmf+vdcFUM7jxG5uJt75NyPETId2zOuBfuc1TWEaUUKa71w+RPqGXV0mIyDslET/FWMxZBGNVE+tQ24Fqe+tcJgzlYlAUTlDeN/PX+Ikl6fowpwTo5QB14vcwKpbo5T5NsDXVBzytj0lh86QR2nWYiMIFJIF+RC5iZ1GjPGnr9p9CAljyVVFjfbF6VLCSiHGvaW4fq+jjKHATHZxwd65PVAfcwUzTjOoAG2tybLi1/D3dKlkQr7JH9oqi5vc0MHQKTmaDMZyUDQeuJ+PPJWlPiu5LRNKBsfO8nsdtsHmNSo92Iog6E5Bwx/RG8nhw89TAjCsCee+JihRLpqjtWPgH1sFQKjR6XCWHgCwV2KhnrmaqV2LSl2GIwAMvbFLUIY14oz/Y1xJ//BPo99exM0s51QqGxCtI3ROLoRoWqVZXaEsBNP13PZ7/iGt3hQoVT6KIEG0bkIHiRnrDGBfXap8dSK4nM5Me4uOd7sEUkEGQpLdg0F7D38Scdwy9ccQmiq+IsrVYJJIX8i2/BYOSn5rf8p7GN5ljYsWN3edIPKBoIsgndot2Zkgkfc10iCMRecwK1wsYPp7nyItOm2ZrhK9MaUMXRusYafIeh7EGgz6loQRjK0lXaf6MUdE9Z2U7AaFmQpoX3bjCt+wjURJ8GBBfGI5ZwRTi//C/bLtOGx9zz7LzFLsnWCRSA5qHpMF/wFgJGJW2uVHWxhSgN0lm+V9wQTcRtSZSPKjW1Xt/U5sehdunAy8X4Wx4AuonA==
