apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  template:
    metadata:
      name: argocd-image-updater-secret
      namespace: argocd
    type: Opaque
  encryptedData:
    webhook.ghcr-secret: AgBVh3u9gxIgch5afYChjlBb9Jb4V9K9UhCIGwQSUUNu4ozTYxo6ozNERshyGKzodmZDpYqr44rD/FnnEhNsf1jIHwAJvZhwdOgcx29Qzvj9gpFnwIVda4GQ77B756dCxZDzxXgfh/rDdZI78bSG7pNPY9J8Ry41tENafyGGXWr9X5Bukma7yO2zIZEg+SuzBrKdjuUfbl+NBWv2IcKH2B8SFSsJBZPiLrhqdqIfi9gAXCd81ImsxBuVJZkZAT1aulWjkab2Lo0przgQiIzlr31O2lf4qQTZ8QXSurpkHv1I+InjPnj6T5LsSQ6vOJ/Iz/KVKSHPGXN268iRSMf28CYe8m9gIkOj+4pgPJmUaZLlFbpU7s6vROn3m3z+DjvAac3iiIJWHUMAUnyalFKRjeRamkk9UA8xEHoHTyxcZSh5ZZdSr8csHc1iczyJ3jLk0Vcr5ugI2bc8IjpP65bLk1D4rcA3sHBtYl484UD0N/gCOJJtXq1zg29Zlf1NKZic+/EWrxHrBxqnM4RAysnGuA9rExDEFKdbvjFTLThFk26sZ9FU4Isv9OoGYbO9d1WXAbtALeVxyQRuw7NbX7cirn8KF5BPDbtms16xocn7H96LfxeGopBciERUT/EOE9hVCnwcjjEizLG80wcQFmgJ0i/wqnHVE6ZD+/NCuY76j7udidcvgI8Om80OhNQrsYbdwaSIGeVmCZmYKDX6ePU0XK3C
