apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netflow-egress-baner
  namespace: bwlimit
spec:
  selector:
    matchLabels:
      app: netflow-egress-baner
  template:
    metadata:
      labels:
        app: netflow-egress-baner
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: "Exists"
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: baner
          image: {{ .Values.nfdumpban.image | default "ghcr.io/pmh-only/nfdumpban:latest" }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NETFLOW_DIR
              value: /data
            - name: THRESHOLD_BYTES
              value: "10737418240"
            - name: INTERVAL_SEC
              value: "2"
            - name: IPSET_NAME
              value: "ban_egress_dst"
          securityContext:
            privileged: true
          volumeMounts:
            - name: netflow
              mountPath: /data
              readOnly: false
            - name: netflow-ban
              mountPath: /var/lib/netflow-ban
              readOnly: false
      volumes:
        - name: netflow
          hostPath:
            path: /var/netflow
            type: DirectoryOrCreate
        - name: netflow-ban
          hostPath:
            path: /var/netflow-ban
            type: DirectoryOrCreate
