apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bwlimit
  namespace: argocd
spec:
  destination:
    namespace: bwlimit
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/bwlimit
    repoURL: git@github.com:pmh-only/ftp.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
