apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  destination:
    namespace: goldilocks
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: goldilocks
    helm:
      values: |-
        vpa:
          enabled: true
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
