apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argocd-image-updater
    helm:
      values: |-
        fullnameOverride: argocd-image-updater
        config:
          registries:
          - name: Github Registry
            prefix: ghcr.io
            api_url: https://ghcr.io
            credentials: pullsecret:core/registry-secret
        extraArgs:
          - --interval=30s
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
