apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: stats
spec:
  template:
    metadata:
      name: registry-secret
      namespace: stats
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgC02X4MAwsfZ2zSZvkLUkNCzn6ZNEiw6JBGLfu8iWTylLoCVthVWoFDWF3bHMl3HEJZ3g9p7/lZLUVMzXylRne+ciE0BWkobI4u5Bc8NB3mkGLHdK3uVJTaaCaOOFPvOBYEJ4CUCQdcpgrxDbPaUonOhpjHVDVE05gGZIvYgZVuxO6E+dfkqgMOeZDRmNe+67pxoGXOrVIzBNArRvM8SyTx2lbqkhyklh2BDVxpIgiTHNTvGP/rA/d2DnFtm52jto2ZKaIQwjgOy8PeIO9pKCWQasBKbvcKlyXm39moqjU7NFzS8vJQXKcPPOkTuWG/cVbNbH4TvoL+E3eXhpdCzicA37Eks5ppkw7KTNlu1VGlzQDc/vZ1j+Zqh3UFeX/ijgG0Bh2qjQJvhytBe/m2gM1yAG5H3LSs8tAgYIZ+I3v22JvnZwBGxGBXBlQdP+yZrdW1eg1TUulX0rTzm/LM9+otGn0iKLTV8UTbjIcjM7Hv5H7bl79XC8Vo7wjRmfyb6E6jMKyUoqa4L2vxV/HZdTW2K44UPotwIUwvXRKBNtmzJirfnuRTjc5wscRC1jlXeQSmwnT0+7sVdWPmPsQFOAtsoXoc3S6WYfBbK0pGvctI16Qgq2LvXqdcgKyx0fPTe95S28QscR3VbFYaTEyKl82Sp+wW5pyYw1Nwan1p6kqJfWskv6L1dxVFYvRz+rCmcoUe8mhSRrFe8jY6agPrL+TsarJ7Xa5UAf5PcAv4BtTNJKOUCRmNHATqpl6WVaVOe3ZVcq5eXGlfI+2p+FXLUBKVdA14vLnad4vZg1Wxb/K4WnJk0byAwKxAY2jRi3sUFWDEEQTmJtsb2rjIOhN4Edxyy53HiRkqe1aba7Uk7h7iIxprmQV+VQN18jD2GWOGs3Al58eKBVS2TxcGUS2kbm6TSPLU1EQgB864UuIUFOqA7kVYyhJpfg==
