apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipv6edge
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ipv6edge
  template:
    metadata:
      labels:
        app: ipv6edge
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: nftables
        image: alpine:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        command:
          - /bin/sh
          - -c
          - |
            sysctl -w net.ipv4.ip_forward=1
            sysctl -w net.ipv6.conf.all.forwarding=1

            nft add table inet nat || true

            nft add chain inet nat prerouting \
              { type nat hook prerouting priority dstnat; } || true

            nft add chain inet nat postrouting \
              { type nat hook postrouting priority srcnat; } || true

            nft add rule inet nat prerouting \
              ip6 daddr :: \
              tcp dport { 80,443,20,21,873,874,30000-30100 } \
              dnat to 127.0.0.1

            nft add rule inet nat prerouting \
              ip6 daddr :: \
              udp dport 443 \
              dnat to 127.0.0.1

            nft add rule inet nat postrouting \
              ip daddr 127.0.0.1 \
              masquerade

            sleep infinity
