apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipv6edge
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ipv6edge
  template:
    metadata:
      labels:
        app: ipv6edge
    spec:
      hostNetwork: true
      containers:
      - name: nftables
        image: alpine:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        command:
          - /bin/sh
          - -c
          - |
            set -e

            apk add --no-cache nftables iproute2

            sysctl -w net.ipv4.ip_forward=1
            sysctl -w net.ipv6.conf.all.forwarding=1

            nft -f - <<'EOF'
            table ip6 nat {
              chain prerouting {
                type nat hook prerouting priority dstnat;

                tcp dport { 80, 443, 20, 21, 873, 874, 30000-30100 } dnat to 127.0.0.1
                udp dport 443 dnat to 127.0.0.1
              }
            }

            table ip nat {
              chain postrouting {
                type nat hook postrouting priority srcnat;
                ip daddr 127.0.0.1 masquerade
              }
            }
            EOF

            sleep infinity
