FROM debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends pmacct ca-certificates \
 && rm -rf /var/lib/apt/lists/*

CMD ["pmacctd","-f","/etc/pmacct/pmacctd.conf"]
