apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: "hpa-{{ .Values.nodeName }}"
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "webserver-{{ .Values.nodeName }}"
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75