apiVersion: apps/v1
kind: Deployment
metadata:
  name: "indexer-{{ .Values.nodeName }}"
  namespace: core
  labels:
    app: indexer
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: indexer
      node: {{ .Values.nodeName }}
  template:
    metadata:
      labels:
        app: indexer
        node: {{ .Values.nodeName }}
    spec:
      priorityClassName: other-core
      nodeName: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: indexer
          image: {{ .Values.indexer.image | default "ghcr.io/pmh-only/indexer:latest" }}
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              memory: 200Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "core-{{ .Values.nodeName }}-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: "indexer-{{ .Values.nodeName }}"
  namespace: core
spec:
  selector:
    app: indexer
    node: {{ .Values.nodeName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: "indexer-{{ .Values.nodeName }}-hpa"
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "indexer-{{ .Values.nodeName }}"
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
