apiVersion: apps/v1
kind: Deployment
metadata:
  name: "indexer-{{ .Values.nodeName }}"
  namespace: core
  labels:
    app: indexer
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: indexer
      node: {{ .Values.nodeName }}
  template:
    metadata:
      labels:
        app: indexer
        node: {{ .Values.nodeName }}
    spec:
      priorityClassName: other-core
      nodeName: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: indexer
          image: {{ .Values.indexer.image | default "ghcr.io/pmh-only/indexer:latest" }}
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "core-{{ .Values.nodeName }}-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: "indexer-{{ .Values.nodeName }}"
  namespace: core
spec:
  selector:
    app: indexer
    node: {{ .Values.nodeName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
