apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rsyncserver-{{ .Values.nodeName }}"
  namespace: core
  labels:
    app: rsyncserver
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rsyncserver
      node: {{ .Values.nodeName }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rsyncserver
        node: {{ .Values.nodeName }}
    spec:
      nodeName: {{ .Values.nodeName }}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: waitforinitsync
          image: alpine:latest
          command:
            - sh
            - -c
            - while [[ ! -f /data/initsync.lck ]]; do sleep 1; done
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
      containers:
        - name: rsyncd
          image: {{ .Values.rsyncserver.image | default "ghcr.io/pmh-only/rsyncserver:latest" }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              memory: 200Mi
          volumeMounts:
            - name: data
              mountPath: /data/static
              subPath: static
              readOnly: true
            - name: config
              subPath: rsyncd.conf
              mountPath: /etc/rsyncd.conf
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "core-{{ .Values.nodeName }}-pvc"
        - name: config
          configMap:
            name: "rsyncserver-{{ .Values.nodeName }}-config"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: "rsyncserver-{{ .Values.nodeName }}-hpa"
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "rsyncserver-{{ .Values.nodeName }}"
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "rsyncserver-{{ .Values.nodeName }}-config"
  namespace: core
data:
  rsyncd.conf: |
    uid = nobody
    gid = nogroup
    use chroot = no
    max connections = 50
    timeout = 600
    transfer logging = false
    log file = /dev/null

    [arch]
      path = /data/static
      comment = Arch Linux mirror (read-only)
      read only = yes
      list = yes
