apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "syncrepo-{{ .Values.nodeName }}"
  namespace: core
  labels:
    app: syncrepo
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: syncrepo
      node: {{ .Values.nodeName }}
  template:
    metadata:
      labels:
        app: syncrepo
        node: {{ .Values.nodeName }}
    spec:
      priorityClassName: other-core
      nodeName: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: initsync
          image: {{ .Values.syncrepo.image | default "ghcr.io/pmh-only/syncrepo:latest" }}
          tty: true
          env:
            - name: SYNC_MODE
              value: initsync
            - name: SOURCE_URL
              value: rsync://taipei.mirror.pkgbuild.com/packages/
            - name: LASTUPDATE_URL
              value: https://taipei.mirror.pkgbuild.com/lastupdate
            - name: INDEXER_URL
              value: "http://indexer-{{ .Values.nodeName }}:8080"
          volumeMounts:
          - name: data
            mountPath: /data
      containers:
      - name: syncrepo
        image: {{ .Values.syncrepo.image | default "ghcr.io/pmh-only/syncrepo:latest" }}
        tty: true
        env:
          - name: SOURCE_URL
            value: rsync://mirror.funami.tech/arch/
          - name: LASTUPDATE_URL
            value: https://mirror.funami.tech/arch/lastupdate
          - name: INDEXER_URL
            value: "http://indexer-{{ .Values.nodeName }}:8080"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "core-{{ .Values.nodeName }}-pvc"
