apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "syncrepo-{{ .Values.nodeName }}"
spec:
  selector:
    matchLabels:
      app: syncrepo
      node: {{ .Values.nodeName }}
  template:
    metadata:
      labels:
        app: syncrepo
        node: {{ .Values.nodeName }}
    spec:
      nodeName: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: initsync
          image: {{ .Values.syncrepo.image | default "ghcr.io/pmh-only/syncrepo:latest" }}
          tty: true
          env:
            - name: SYNC_MODE
              value: initsync
            - name: SOURCE_URL
              value: rsync://mirror.rackspace.com/archlinux/
            - name: LASTUPDATE_URL
              value: https://mirror.rackspace.com/archlinux/lastupdate
          volumeMounts:
          - name: data
            mountPath: /data
      containers:
      - name: syncrepo
        image: "ghcr.io/pmh-only/syncrepo:{{ .Values.syncrepo.tag | default "latest" }}"
        tty: true
        env:
          - name: SOURCE_URL
            value: rsync://mirror.funami.tech/arch/
          - name: LASTUPDATE_URL
            value: https://mirror.funami.tech/arch/lastupdate
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "core-{{ .Values.nodeName }}-pvc"
