apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webserver-{{ .Values.nodeName }}"
  namespace: core
  labels:
    app: webserver
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: webserver
      node: {{ .Values.nodeName }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webserver
        node: {{ .Values.nodeName }}
    spec:
      priorityClassName: webserver
      nodeName: {{ .Values.nodeName }}
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-secret
      initContainers:
        - name: waitforinitsync
          image: alpine:latest
          command:
            - sh
            - -c
            - while [[ ! -f /data/initsync.lck ]]; do sleep 1; done
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
      containers:
        - name: webserver
          image: {{ .Values.webserver.image | default "ghcr.io/pmh-only/webserver:latest" }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: '1'
              memory: 200Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl -f http://localhost:80/healthz || exit 1
            initialDelaySeconds: 5
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl -f http://localhost:80/healthz || exit 1
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 443
              protocol: UDP
              name: http3
          env:
            - name: NODE_NAME
              value: {{ .Values.nodeName }}
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/tls
              readOnly: true
            - name: data
              mountPath: /data
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: tls-secret
        - name: data
          persistentVolumeClaim:
            claimName: "core-{{ .Values.nodeName }}-pvc"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: "webserver-{{ .Values.nodeName }}-hpa"
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "webserver-{{ .Values.nodeName }}"
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
