apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: core
spec:
  dnsNames:
    - ftp.io.kr
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt
  secretName: tls-secret
  privateKey:
    algorithm: ECDSA
    size: 384
  usages:
    - digital signature
    - key encipherment
