apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: core
spec:
  template:
    metadata:
      name: cloudflare-secret
      namespace: core
    type: Opaque
  encryptedData:
    api-token: AgANqbI8ioho0VPiOjiD2x0wF2dc44trHt2bm+ymKX5TOc/71jblYLIQJpn09Qmw+qfowj2UtX0s18IIiy4ypuXDWrCoM9N+HBTEKw1XP1y7gOejL5qF3lEJRPZaz01qfWJfP4Ai5qpAm4e/sayEGsn1aTVa9GaIxVlIwuoZS60pAOqY8aV7mH+vXNcvVZChEO2ReaOQEVyIM99L9c/Krgxz27WgmMWFIW/NDeS4jX3aYS25dqJ4+RVmYFr2alqSuaZkgvHVhknYhmo2cq+Bylajr4zlh7x3wUIcQR1fE3T7EvTfNQNEl3cxgGepW1B6IUF6dRoBPRtSrGFqU+zm648WumfsNqfdM5WBJAork2WfV7dxqwDCu9JZzm5nA4eGemC6F/iWbCBgVpbcwf4Klmprs7MCBZpzmEI++b0FXoiDvgiXyziydtRDgyPSmLw4H2cnbh2aSpPFkpo99tOvyEVQmJ3nescUYUWBqysaV/oUN5/nIdwFH9RzWFXEaT106rFc+eD0Cvv0x29UEq3IRHHO2OKkx6cyg5/eePynmxA3l3F27yl75A1W7sSO5q1WPJLmNMsGRQfzhO9HVCPPOPX0GP4IfC4G9FFK4rmahNYI7FAS67HUVNi1NJz9+Pcy7b0YcjCALORX9dthWRISr0NxfCBCZ7UtWkDOg90VoBT90gHmRJ69s/vexboLVh1avY7H59A/+pJjfrh8/7ihY4ThnUAOrBNotbLcktRLwkE5eIv11bC8x4m8
