apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: core
spec:
  acme:
    email: pmh_only@pmh.codes
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    preferredChain: "ISRG Root X2"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secret
              key: api-token
        selector:
          dnsZones:
            - ftp.io.kr
