apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: net
spec:
  template:
    type: Opaque
    metadata:
      name: operator-oauth
      namespace: net
  encryptedData:
    client_id: AgAvtuVVZDL4TUsiZALTFOq0ZOCcrOhjOYaWTEfo70VWAV4Ov4mMt/BCjML83sH0UIIovkWU4r5nkglLXHy4Cboac315kbZ98Utlhg0Hqwax2Z0iNIenBnpYuQdskJzlFc5At371snmT07/yh4nzSCEEP00esUkchYV8dtcMC9elOYDLQyGBZCCmWJ7aC1jGqXgopAxeSkxckKvdHK2lC243KWNpJCFOXSNSa1dV2nV/UbqFbYBAuGDb9Sx7KAkQwyGF9GkP4OVIF3yX6KO+d+yuTNsfdNLz34fFug/bLaNILOSUFA2q+ZfszlwBFZFKxMj5L5c08jPq7Do76Rzq5XF0QufJZZA2r4BLN5nKSdnLGTLFmbGqjjcF62S3P77P0iaGlg1vgG3HUczepyW4O4/KS/zvAlRmGvBtVki2bYynADN+uuVCkLzvxCmFTuUb9Jvo8+OzNfdhkIGodpRzepq9ic1ptrnoGa/8nFbR4X8t2qtBp12pER++DrdQIlKJTxWTg2KAdkAK/G1n0Yed/D4UI8vYiPyLpNAdmGew7LdiiWQYTXEJb6PRiG4ILdY0P9X/L/8GsX5VzLEs1hooMf7imvglst4TBLDEG2zKLlVNsoAILaHhjChhtlpNdTmcIAqBgyP49ZzjrHD559aHusQHraAQgVBf76ujDoKjtesULWnEpxf9RijXx3eBVu2jKK5YR6ZqtNgogfOsoCIUmz5wWQ==
    client_secret: AgAS5snAFlt5VvzPfYOPS+5TX07rB6VbHwVWvxVCaJXmpjjk5xBpXV+h8Vo+UNqFpV2ssbkz0QjS8Aeb7L2PbTSn1slXoO4NBswfy4tq80DPqfKzm/PFAxOZgeGJoBLRFSfqNQuW7xU6gPVg/PVVXt2aamCvWEs6vDC7gVb6aPMi6ep3csNpcRgeEOVvRF5X0lNaXmCYa7DS0eoUI6xP6ViSJh0W5pKBT1lS87+b8bhZHvbzGO9A8IwCtyEcKoNFLvWmwFgnT7YH0oGwPnDWjmWt59gd+TxlSsuJZAhOnSSCVbReZH+8CVja2uAwiCp66pWdhmyx/illqa4eDXrhFSx/QFLtS2Vmulvykp/9xqLjZPOwdeC2ECr3cug8vc753rvWIKtDDM5DLtynupKKgsrS9Sb6NENLkxmoVQYJ9DULSWNbI0Ys2/uNRCOW/thjzCXIKev38kolVvh95VwjspetJsjaV32gHaqL3HJaxUxE75L202gVnyQEd++eaz/8ghwBRg5o+0+z6AzzJYyVmvtsNhZQcqam4GZczvoYOK8kiAiBUQIhHWue3F1oQe3TFI2tc2/OoYARq876K9KcTvrNQbBs9q0LgDrLGtGWoLXsFh07RrZZu7rkn7UIQkhFg78hqDtkTSL8dBuPgTXn59TmVShpexFGreOlJ0O7CglivRAZLJkE2w67Js6Xaf62SsvVo2BJecWHxjernGBPIq7TK94zHPnWaZOTkKo54OsEUFIRAcds8HbOIMwn/sIHs0QLfI1/RQdjWD8Qu6CFuM0=
